project_id = "awvwrdjtptjyalmsyejt"

[functions.detect-text]
 verify_jwt = true
 
 [functions.generate-flashcards]
 verify_jwt = false

 [functions.waitlist-signup]
 verify_jwt = false

 [functions.waitlist-count]
 verify_jwt = false

 [functions.process-email-queue]
 verify_jwt = true
