import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

const MAX_FLASHCARDS = 100;
const MAX_CONTENT_CHARS = 120000;
// Documents are split into sections of roughly this size, each generated by
// its own AI call with an explicit per-section card quota. Small focused
// tasks with exact targets are covered reliably; one big "make many cards"
// task gets undershot.
const SECTION_TARGET_CHARS = 3000;
const MAX_SECTIONS = 12;

interface Flashcard {
  term: string;
  definition: string;
}

// Recovers complete card objects from a JSON string that may be truncated
// (e.g. a large tool-call payload cut off mid-stream). Scans the flashcards
// array and parses each complete top-level object, skipping any partial
// trailing one.
function salvageFlashcards(raw: string): Flashcard[] {
  const cards: Flashcard[] = [];
  const start = raw.indexOf('[');
  if (start === -1) return cards;
  let depth = 0;
  let objStart = -1;
  let inString = false;
  let escaped = false;
  for (let i = start + 1; i < raw.length; i++) {
    const ch = raw[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === '\\') escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') { inString = true; continue; }
    if (ch === '{') { if (depth === 0) objStart = i; depth++; }
    else if (ch === '}') {
      depth--;
      if (depth === 0 && objStart !== -1) {
        try { cards.push(JSON.parse(raw.slice(objStart, i + 1))); } catch { /* skip partial */ }
        objStart = -1;
      }
    } else if (ch === ']' && depth === 0) break;
  }
  return cards;
}

// Splits text that has no usable paragraph breaks into pieces of at most
// `size` chars, cutting at the nearest space when possible.
function hardSplit(text: string, size: number): string[] {
  const parts: string[] = [];
  let i = 0;
  while (i < text.length) {
    let end = Math.min(i + size, text.length);
    if (end < text.length) {
      const lastSpace = text.lastIndexOf(' ', end);
      if (lastSpace > i + size * 0.5) end = lastSpace;
    }
    parts.push(text.slice(i, end));
    i = end;
  }
  return parts;
}

// Splits the document into sections at paragraph boundaries, keeping each
// section near SECTION_TARGET_CHARS and the section count at most
// MAX_SECTIONS (sections grow for very long documents).
function splitIntoSections(content: string): string[] {
  if (content.length <= SECTION_TARGET_CHARS * 1.3) return [content];
  const sectionSize = Math.max(SECTION_TARGET_CHARS, Math.ceil(content.length / MAX_SECTIONS));

  const paragraphs: string[] = [];
  for (const p of content.split(/\n\s*\n/)) {
    if (p.length > sectionSize) paragraphs.push(...hardSplit(p, sectionSize));
    else paragraphs.push(p);
  }

  const sections: string[] = [];
  let current = '';
  for (const p of paragraphs) {
    if (current && current.length + p.length + 2 > sectionSize) {
      sections.push(current);
      current = p;
    } else {
      current = current ? current + '\n\n' + p : p;
    }
  }
  if (current.trim()) sections.push(current);
  return sections;
}

// How many cards a section of this size should produce.
function cardTargetFor(chars: number): number {
  // Denser coverage: ~1 card per 130 chars, with a healthy floor so short
  // documents still produce a substantial set.
  return Math.min(40, Math.max(15, Math.round(chars / 130)));
}

const systemPrompt = `You are an expert educator creating exam-focused flashcards optimized for long-term understanding, active recall, and assessment preparation.

You will receive either a full document or one section of a larger document, along with a target number of flashcards. Treat the target as a strong requirement: produce that many flashcards covering the provided content thoroughly. Only produce fewer if the content genuinely cannot support the target without duplicates or filler.

COVERAGE:
- Cover EVERY topic and subtopic in the provided content.
- Prioritize high-yield information most likely to appear on quizzes and exams.
- Include important definitions, processes, mechanisms, formulas, relationships, comparisons, cause-and-effect concepts, exceptions, and high-yield facts (specific percentages, thresholds, years, categories, named frameworks/laws/models).
- Where the content describes charts, tables, figures, or diagrams, turn their key takeaways into flashcards (notable values, rankings, trends, and what they imply).
- Break complex concepts into several smaller, memorable flashcards rather than one long card.

CARD FORMATS — for each concept, INDEPENDENTLY choose the format that best reinforces it, and naturally mix styles across the set:
1. Term ↔ Definition — vocabulary, named laws/acts/frameworks, classifications, structures, formulas.
2. Question ↔ Answer — mechanisms, "why" and "how" concepts, multi-step processes, applied reasoning.
3. Comparison cards — "What is the difference between X and Y?" for contrasting concepts.
4. Cause/effect cards — "Why does X lead to Y?" for relationships and consequences.
5. Example-based cards — tie abstract concepts to concrete examples from the material.
6. Application/exam-style cards — deeper "why/how" questions a professor would ask on an exam.
7. Simplified-explanation cards — for complex topics, the answer explains the idea in a simple, easy-to-understand way while staying accurate to the material.
Never ask the user to pick a format — decide automatically per concept. Straightforward facts → term/definition. Complex or applied ideas → question/answer or explanation cards.

CARD QUALITY:
- Each flashcard must be concise, accurate, and focused on ONE key idea.
- Answers must be complete enough to actually learn from — avoid vague one-liners — but without unnecessary length.
- When a topic is complex, explain it simply (plain language, brief reasoning, or a quick example) while staying accurate to the provided material.
- Preserve important terminology exactly where appropriate.
- Order cards to follow the order of the provided content.
- Avoid duplicate or repetitive cards and filler/overly obvious cards.
- Always populate the "term" field with the FRONT of the card (either the term OR the question) and the "definition" field with the BACK of the card (either the definition OR the answer). Do not add labels like "Q:" or "A:".`;

// Calls the AI gateway with retries on rate limits and transient errors.
async function callGateway(apiKey: string, body: unknown): Promise<{ data: any | null; status: number }> {
  let lastStatus = 500;
  for (let attempt = 0; attempt < 3; attempt++) {
    if (attempt > 0) await new Promise((r) => setTimeout(r, 2000 * attempt));
    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Lovable-API-Key': apiKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
    });
    if (response.ok) return { data: await response.json(), status: 200 };
    lastStatus = response.status;
    const errorText = await response.text();
    console.error(`AI gateway error (attempt ${attempt + 1}):`, response.status, errorText);
    // Retry only rate limits and server errors.
    if (response.status !== 429 && response.status < 500) break;
  }
  return { data: null, status: lastStatus };
}

// Generates the flashcards for one section of the document.
async function generateSectionCards(
  apiKey: string,
  section: string,
  target: number,
  sectionIndex: number,
  totalSections: number,
): Promise<{ cards: Flashcard[]; errorStatus: number | null }> {
  const sectionLabel = totalSections > 1
    ? `section ${sectionIndex + 1} of ${totalSections} of a larger document`
    : 'material';
  const userMessage = `Generate EXACTLY ${target} exam-prep flashcards from this ${sectionLabel}. This is a firm requirement, not a suggestion — do not stop early. If you are running out of obvious cards, break broader concepts into smaller sub-cards, add comparison, application, and example cards, and cover every named fact, figure, date, definition, mechanism, and subtopic. Only fall short of ${target} if the content is truly too small to support that many non-duplicate cards. Use a natural mix of definition, question/answer, comparison, application, and simplified explanation cards. If a concept is complex, explain it in a simple way.\n\nContent:\n\n${section}`;

  const { data, status } = await callGateway(apiKey, {
    model: 'openai/gpt-5.4',
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userMessage },
    ],
    tools: [
      {
        type: 'function',
        function: {
          name: 'generate_flashcards',
          description: 'Generate exam-prep flashcards from the provided content',
          parameters: {
            type: 'object',
            properties: {
              flashcards: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    term: { type: 'string', description: 'The term or question for the front of the card' },
                    definition: { type: 'string', description: 'The definition or answer for the back of the card' }
                  },
                  required: ['term', 'definition'],
                  additionalProperties: false
                }
              }
            },
            required: ['flashcards'],
            additionalProperties: false
          }
        }
      }
    ],
    tool_choice: { type: 'function', function: { name: 'generate_flashcards' } },
    // Generous output budget so section payloads are never cut off by a low
    // gateway default.
    max_completion_tokens: 16384,
  });

  if (!data) return { cards: [], errorStatus: status };

  let cards: Flashcard[] = [];
  const toolCalls = data.choices?.[0]?.message?.tool_calls;
  if (toolCalls && toolCalls.length > 0) {
    const rawArgs = toolCalls[0].function.arguments;
    try {
      const args = JSON.parse(rawArgs);
      cards = args.flashcards || [];
    } catch (parseError) {
      // Large outputs can occasionally be truncated mid-JSON; recover every
      // complete card instead of failing the section.
      console.error(`Section ${sectionIndex + 1}: failed to parse tool arguments, salvaging:`, parseError);
      cards = salvageFlashcards(rawArgs);
    }
  } else {
    // Fallback: try to parse from message content if no tool calls
    const messageContent = data.choices?.[0]?.message?.content;
    if (messageContent) {
      try {
        const jsonMatch = messageContent.match(/\[[\s\S]*\]/);
        if (jsonMatch) cards = JSON.parse(jsonMatch[0]);
      } catch (parseError) {
        console.error(`Section ${sectionIndex + 1}: failed to parse content as JSON:`, parseError);
      }
    }
  }

  const validCards = (Array.isArray(cards) ? cards : []).filter(
    (c) => c && typeof c.term === 'string' && typeof c.definition === 'string' && c.term.trim() && c.definition.trim()
  );
  console.log(`Section ${sectionIndex + 1}/${totalSections}: target ${target}, got ${validCards.length} cards`);
  return { cards: validCards, errorStatus: null };
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { content } = await req.json();

    if (!content || typeof content !== 'string') {
      return new Response(JSON.stringify({ error: 'Content is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      console.error('LOVABLE_API_KEY is not configured');
      return new Response(JSON.stringify({ error: 'AI service not configured' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const trimmedContent = content.substring(0, MAX_CONTENT_CHARS);
    const sections = splitIntoSections(trimmedContent);

    // Per-section quotas, scaled down proportionally if they would exceed
    // the overall maximum.
    let targets = sections.map((s) => cardTargetFor(s.length));
    const totalTarget = targets.reduce((a, b) => a + b, 0);
    if (totalTarget > MAX_FLASHCARDS) {
      targets = targets.map((t) => Math.max(5, Math.floor((t * MAX_FLASHCARDS) / totalTarget)));
    }

    console.log(`Generating flashcards: ${trimmedContent.length} chars, ${sections.length} section(s), targets: ${targets.join(', ')}`);

    // Sections run in parallel so large documents stay fast.
    const results = await Promise.all(
      sections.map((section, i) =>
        generateSectionCards(LOVABLE_API_KEY, section, targets[i], i, sections.length)
          .catch((err) => {
            console.error(`Section ${i + 1} failed:`, err);
            return { cards: [] as Flashcard[], errorStatus: 500 };
          })
      )
    );

    // Combine in document order, drop duplicate fronts across sections,
    // enforce the hard cap.
    const seen = new Set<string>();
    const flashcards: Flashcard[] = [];
    for (const result of results) {
      for (const card of result.cards) {
        const key = card.term.trim().toLowerCase().replace(/[^a-z0-9 ]/g, '');
        if (seen.has(key)) continue;
        seen.add(key);
        flashcards.push(card);
        if (flashcards.length >= MAX_FLASHCARDS) break;
      }
      if (flashcards.length >= MAX_FLASHCARDS) break;
    }

    if (flashcards.length === 0) {
      const errorStatuses = results.map((r) => r.errorStatus).filter((s): s is number => s !== null);
      if (errorStatuses.includes(402)) {
        return new Response(JSON.stringify({ error: 'AI credits exhausted. Please add credits to continue.' }), {
          status: 402,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      if (errorStatuses.includes(429)) {
        return new Response(JSON.stringify({ error: 'Rate limit exceeded. Please try again in a moment.' }), {
          status: 429,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      if (errorStatuses.length > 0) {
        return new Response(JSON.stringify({ error: 'AI generation failed' }), {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      return new Response(JSON.stringify({ error: 'No flashcards could be generated from this content' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log(`Generated ${flashcards.length} flashcards from ${sections.length} section(s)`);

    return new Response(JSON.stringify({ flashcards }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('generate-flashcards error:', error);
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
