// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-flashcard-sets.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-flashcard-sets.ts
var list_flashcard_sets_default = defineTool({
  name: "list_flashcard_sets",
  title: "List flashcard sets",
  description: "List the signed-in user's flashcard sets, most recently updated first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max number of sets to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("flashcard_sets").select("id, title, description, color, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { sets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-flashcard-set.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_flashcard_set_default = defineTool2({
  name: "get_flashcard_set",
  title: "Get flashcard set",
  description: "Read a single flashcard set and all of its flashcards (term, definition, position).",
  inputSchema: {
    set_id: z2.string().uuid().describe("The flashcard set id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ set_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data: set, error: setErr } = await supabase.from("flashcard_sets").select("id, title, description, color, created_at, updated_at").eq("id", set_id).maybeSingle();
    if (setErr) return { content: [{ type: "text", text: setErr.message }], isError: true };
    if (!set) return { content: [{ type: "text", text: "Set not found" }], isError: true };
    const { data: cards, error: cardErr } = await supabase.from("flashcards").select("id, term, definition, position, flashcard_type, is_bookmarked").eq("set_id", set_id).order("position", { ascending: true });
    if (cardErr) return { content: [{ type: "text", text: cardErr.message }], isError: true };
    const payload = { set, flashcards: cards ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-flashcard-set.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_flashcard_set_default = defineTool3({
  name: "create_flashcard_set",
  title: "Create flashcard set",
  description: "Create a new empty flashcard set for the signed-in user.",
  inputSchema: {
    title: z3.string().trim().min(1).max(200),
    description: z3.string().max(2e3).optional(),
    color: z3.string().max(32).optional().describe("Hex color like #38b6ff.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, color }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("flashcard_sets").insert({ user_id: ctx.getUserId(), title, description: description ?? null, color: color ?? "#000000" }).select("id, title, description, color").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { set: data }
    };
  }
});

// src/lib/mcp/tools/create-flashcard.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_flashcard_default = defineTool4({
  name: "create_flashcard",
  title: "Create flashcard",
  description: "Add a standard term/definition flashcard to an existing set owned by the signed-in user.",
  inputSchema: {
    set_id: z4.string().uuid(),
    term: z4.string().trim().min(1).max(2e3),
    definition: z4.string().trim().min(1).max(4e3)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ set_id, term, definition }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data: last } = await supabase.from("flashcards").select("position").eq("set_id", set_id).order("position", { ascending: false }).limit(1);
    const nextPosition = (last?.[0]?.position ?? -1) + 1;
    const { data, error } = await supabase.from("flashcards").insert({ set_id, term, definition, position: nextPosition, flashcard_type: "standard" }).select("id, term, definition, position").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { flashcard: data }
    };
  }
});

// src/lib/mcp/tools/delete-flashcard.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.25.76";
var delete_flashcard_default = defineTool5({
  name: "delete_flashcard",
  title: "Delete flashcard",
  description: "Delete a single flashcard by id from a set owned by the signed-in user.",
  inputSchema: {
    flashcard_id: z5.string().uuid()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ flashcard_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("flashcards").delete().eq("id", flashcard_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Deleted ${flashcard_id}` }], structuredContent: { deleted: flashcard_id } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "awvwrdjtptjyalmsyejt";
var mcp_default = defineMcp({
  name: "phormula-mcp",
  title: "Phormula",
  version: "0.1.0",
  instructions: "Tools for the Phormula flashcard app. List a user's flashcard sets, read the cards in a set, and create or delete flashcards on the signed-in user's account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_flashcard_sets_default,
    get_flashcard_set_default,
    create_flashcard_set_default,
    create_flashcard_default,
    delete_flashcard_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
